spring:
  application:
    name: CarService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/copyria"
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: sql
    password: sql
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      bindings:
        on-car-deleted-event-out-0:
          destination: copyria.car.event.v1.car-deleted-events
app:
  apis:
    car-service:
      base-url: "http://localhost:8081/"
server:
  port: 8080