spring:
  application:
    name: CarService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://keycloak:8080/realms/copyria"
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://database:5432/db
    username: sql
    password: sql
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: kafka-broker:29092
          auto-create-topics: true
      bindings:
        on-car-deleted-event-out-0:
          destination: copyria.car.event.v1.car-deleted-events
app:
  apis:
    car-service:
      base-url: "http://order_service:8081/"
server:
  port: 8082