spring:
  application:
    name: OrderService
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: sql
    password: sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      WRITE-DATES-AS-TIMESTAMPS: false
  liquibase:
    enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: "http://localhost:9090/realms/copyria/protocol/openid-connect/token"
        registration:
          order-service-client:
            authorization-grant-type: client_credentials
            client-id: "order-service-client"
            client-secret: "mYZahmjIkzXPfwfhliokc7Lf3D9s8Mjt"
            provider: keycloak
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/copyria"
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
      function:
        definition: on-car-deleted-event
      bindings:
        on-car-deleted-event-in-0:
          destination: copyria.car.event.v1.car-deleted-events
          group: order-service
app:
  privat:
    url: "https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5"
  apis:
    car-service:
      base-url: "http://localhost:8080/"
server:
  port: 8081